site_name: Artisan Worktables

pages:
  - Introduction: index.md
  - ChangeLog: changelog.md
  - Configuration Files: configuration.md
  - Creating Recipes:
    - Quick Reference: recipes/quickreference.md
    - Getting Started: recipes/gettingstarted.md
    - Basic Recipes: recipes/basic.md
    - Recipe Names: recipes/names.md
    - Table Tiers: recipes/tiers.md
    - Recipes with Tools: recipes/tools.md
    - Recipes with Fluids: recipes/fluids.md
    - Extra Chance Output: recipes/extraoutput.md
    - Weighted Primary Output: recipes/weighted.md
    - Secondary Ingredients: recipes/secondaryingredients.md
    - Experience Requirements: recipes/experiencerequirements.md
    - Copying Recipes: recipes/copying.md
    - Recipe Functions: recipes/functions.md
  - Mod Integrations: 
    - Mod Integrations: integrations/index.md
    - GameStages: integrations/gamestages.md
    - Reskillable: integrations/reskillable.md
  - Tools:
    - Custom Tool Materials: tools/custommaterials.md
  - Development:
    - Contributor's License Agreement: cla.md
    - Workflow: notes/workflow.md

theme: readthedocs

markdown_extensions:
  - admonition